[build]
builder = "NIXPACKS"
buildCommand = """
ln -s /root/.nix-profile/bin/ffmpeg /usr/local/bin/ffmpeg && \
pip install -r requirements.txt
"""

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
NIXPACKS_PKGS = "ffmpeg opus opus-tools libopus0 libopus-dev"
