[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
NIXPACKS_PKGS = "ffmpeg python3-pip opus opus-tools libopus0 libopus-dev"
