[build]
builder = "NIXPACKS"
buildCommand = """
apt-get update && \
apt-get install -y ffmpeg && \
pip install -r requirements.txt
"""

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
NIXPACKS_PKGS = "ffmpeg opus opus-tools python3-pip"
